### ISSUE TITLE
Version links are outdated

### ISSUE THREAD

**Issue by teonbrooks** [mne-tools/mne-tools.github.io#1]
@Eric89GXL The version links are still linked to the martinos website. 
https://github.com/mne-tools/mne-tools.github.io/blame/master/stable/index.html#L116

**Comment by Eric89GXL** [comment]
I think we plan to actually use the Martinos site for hosting, and just use this as the build location. @agramfort are we switching?

**Comment by agramfort** [comment]
Indeed
